.storybook/config.js, gulpfile.js, package.json, tasks/build.js, tasks/build/orionCss.js, yarn.lock
>More explanations about this Orion repo on #chapter_frontend.
The merged CSS files with be called `orion.css` and `orion.min.css`.
=> chore(atomic-bomb): Concat atomic bomb's css with semantic's

src/Dropdown/dropdown.css, src/Label/index.js
=> feature(dropdown): Style the multiple selection dropdown

src/Checkbox/Checkbox.stories.js, src/Checkbox/checkbox.css
Tinha esquecido de estilizar o estado disabled do checkbox.
=> feature(checkbox): Style disabled checkbox

src/Dropdown/dropdown.css, src/Dropdown/index.js
O Dropdown com search precisa de um pouco mais de CSS, por ter um input dentro dele.
=> feature(dropdown): Style dropdown with search

src/Dropdown/index.js, src/Select/Select.stories.js, src/Select/index.js
Select is just sugar for a selection dropdown in Semantic UI. We have to override it to use our own Dropdown instead of theirs.
=> feature(select): Style select

src/Dropdown/Dropdown.stories.js, src/Dropdown/dropdown.css
Vamos precisar dele no novo Layout. Apenas um dropdown simples estilo menu, sem ser um select.
=> feature(dropdown): Style non selection dropdown

src/Dropdown/dropdown.css
=> feature(dropdown): Style error/warning dropdown

src/Checkbox/checkbox.css
Explicação dos passos no GIF (já que não dá pra ver o que estou fazendo com o teclado): 
1. Focus no checkbox através de do teclado.
2. Ativando o checkbox pelo teclado.
3. Tirando o foco do checkbox pelo teclado.
4. Desativando o checkbox pelo teclado.
=> fix(checkbox): Add focus style

components.css, src/Layout/Layout.stories.js, src/Layout/layout.css, src/Menu/Menu.stories.js, src/Menu/menu.css
**Somente o menu:**
**Dentro do Layout.Topbar:**
Nota: o dropdown o lado direito da topbar ainda não está finalizado, tem uns detalhes que vão mostrá-lo mais alinhado no final.
=>  feature(menu): Style a simple Menu

jest.config.js, src/Form/Field/Field.test.js, src/Form/Field/index.js, src/Form/Form.stories.js, src/setupTests.js
Corrigi um bug que @mairatma detectou e fiz os testes.
OBS: o `setupTests.js` só funciona dentro do CRA. Tive que mudar para o config do jest pra poder fazer o cleanup correto (antes disso, passei mais de 1h sem entender porque não estava limpando).
=> tests(form-field): Add tests and fix bug

src/ClickOutside/ClickOutside.test.js, src/ClickOutside/index.js, src/index.js
Um componente bastante útil, e que já vou precisar no nosso novo componente `Filter`.
=> feature(clickOutside): Add ClickOutside component

components.css, src/Button/index.js, src/Popup/Popup.stories.js, src/Popup/popup.css
Só estilizei o popup `basic` por enquanto, que não tem seta apontando pra a posição do trigger:
=>  feature(popup): Style Popup

src/Form/Field/Field.test.js, src/Form/Field/field.css, src/Form/Field/index.js, src/Form/Form.stories.js
Achei melhor sempre adicionar o wrapper.
=> feature(form-field-message): Add message prop

src/Button/Button.stories.js, src/Button/button.css
O comportamento é este mesmo né? Um que é rounded não faz sentido ser fluid?
=> feature(button-fluid): Add css for fluid prop

components.css, package.json, src/Button/index.js, src/Dropdown/dropdown.css, src/Filter/Filter.stories.js, src/Filter/Filter.test.js, src/Filter/filter.css, src/Filter/index.js, src/Popup/popup.css, src/index.js
Nosso componente pra filtros (antigo Boxdown). A idéia é funcionar da mesma forma que [este da Airbnb](https://www.airbnb.com/s/Vancouver--BC--Canada/homes?refinement_paths%5B%5D=%2Fhomes&checkin=2019-07-01&checkout=2019-07-31&search_type=FILTER_CHANGE&zoom=11&search_by_map=true&sw_lat=49.09669803182315&sw_lng=-123.21660865234372&ne_lat=49.38718731161772&ne_lng=-122.80462134765622&place_id=ChIJs0-pQ_FzhlQRi_OBm-qWkbs&allow_override%5B%5D=&room_types%5B%5D=Entire%20home%2Fapt&room_types%5B%5D=Private%20room).
Falta ainda melhorar a interação com teclado, vou fazer em outro pr.
=> feature(filter): Add Filter component

src/Dropdown/Dropdown.stories.js, src/Dropdown/dropdown.css, src/Dropdown/index.js
Possibilita ter um Dropdown com o menu inline, ao invés de em um popup.
=> feature(dropdown): Add prop for enabling inline menu

src/Dropdown/Dropdown.stories.js, src/Dropdown/Dropdown.test.js, src/Dropdown/DropdownKeepSelected/index.js, src/Dropdown/dropdown.css, src/Dropdown/index.js
=> feature(dropdown): Add option for keeping selected options on the multiple dropdown

src/Dropdown/Dropdown.stories.js, src/Dropdown/DropdownItem/dropdown-item.css, src/Dropdown/DropdownItem/index.js, src/Dropdown/dropdown.css, src/Dropdown/index.js
**Dropdown items with description:**
**Truncating long text/description:**
=> feature(dropdown): Style dropdown menu with description

.babelrc, package.json, src/Dropdown/DropdownItem/index.js, src/Dropdown/index.js, src/Filter/index.js, yarn.lock
Ahhhh, fica tão melhor... 🎉 
Confirmei que funciona, os arquivos buildados estão vindo como se eu estivesse dando os imports isolados.
Depois vou ver se consigo aplicar isso no `inloco-front` sem ejetar... 🙏
=>  chore(lodash): Use babel plugin to rewrite lodash imports

package.json, src/Layout/Layout.stories.js, src/Layout/layout.css, yarn.lock
=> feature(layout): Stick topbar on the top when scrolling

src/Filter/filter.css
=> fix(filter): Fix some styles from Filter

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/filter.css, packages/orion/src/Filter/index.js
=> feature(filter): Add prop for passing extra footer content to the Filter popup

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/Dropdown.test.js, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Dropdown/index.js
=> feature(dropdown): Add loading spinner when `loading` prop is enabled

packages/orion/src/Card/Card.stories.js, packages/orion/src/Card/card.css
=> feature(card): Style Card's extra content

packages/orion/src/Popup/Popup.stories.js, packages/orion/src/Popup/popup.css
=> feature(popup): Style popup with the pointing arrow

packages/orion/.storybook/main.css, packages/orion/components.css, packages/orion/src/Dimmer/Dimmer.stories.js, packages/orion/src/Dimmer/dimmer.css
=> feature(dimmer): Add the Dimmer component

packages/atomic-bomb/tailwind.config.js, packages/orion/.storybook/main.css, packages/orion/components.css, packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/table.css, packages/orion/src/index.js
=> feature(table): Add "Table" component

packages/orion/components.css, packages/orion/src/Divider/Divider.stories.js, packages/orion/src/Divider/divider.css, packages/orion/src/Divider/index.js, packages/orion/src/index.js
Vou usar dentro da nossa nova tabela, então já deixei estilizado aqui. É um componente bem simples, mas vale a pena não precisar ficar repetindo quando for usar.
**Sozinho**
**No meio de dois textos**
=> feature(divider): Add "Divider" component

packages/orion/src/Card/card.css
Bruno pediu pra adicionar o shadow-300 no hover e adicionar um transition.
=> feature(Card): change the card shadow and add transition

packages/orion/src/Message/Message.stories.js, packages/orion/src/Message/index.js, packages/orion/src/Message/message.css
Adiciona a property `fluid` no Message pra ele não ter tamanho máximo.
=> feature(Message): add the fluid property

packages/orion/src/Datepicker/Datepicker.stories.js, packages/orion/src/Datepicker/datepicker.css
Faltou estilizar esse caso.
**Antes**
**Depois**
=> feature(datepicker): Style disabled dates

packages/orion/src/Datepicker/datepicker.css, packages/orion/src/RangedDatepicker/RangedDatepicker.stories.js
=> feature(datepicker): Style disabled navigation buttons

packages/orion/src/Wizard/Wizard.stories.js, packages/orion/src/Wizard/index.js
Esse PR adiciona a prop `buttons` no Wizard, para que os `WizardControls` possam ser customizados.
=> feature(Wizard): expose the wizard controls to be customizable

packages/orion/.storybook/config.js, packages/orion/src/Button/Button.stories.js, packages/orion/src/Card/Card.stories.js, packages/orion/src/Checkbox/Checkbox.stories.js, packages/orion/src/Datepicker/Datepicker.stories.js, packages/orion/src/Dimmer/Dimmer.stories.js, packages/orion/src/Divider/Divider.stories.js, packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Form/Form.stories.js, packages/orion/src/FullscreenContainer/FullscreenContainer.stories.js, packages/orion/src/Icon/Icon.stories.js, packages/orion/src/InfoIcon/InfoIcon.stories.js, packages/orion/src/Input/Input.stories.js, packages/orion/src/Label/Label.stories.js, packages/orion/src/Layout/Layout.stories.js, packages/orion/src/Loading/Loading.stories.js, packages/orion/src/Menu/Menu.stories.js, packages/orion/src/Message/Message.stories.js, packages/orion/src/Modal/Modal.stories.js, packages/orion/src/NotificationCenter/NotificationCenter.stories.js, packages/orion/src/Popup/Popup.stories.js, packages/orion/src/Progress/Progress.stories.js, packages/orion/src/RangedDatepicker/RangedDatepicker.stories.js, packages/orion/src/Search/Search.stories.js, packages/orion/src/Select/Select.stories.js, packages/orion/src/StepsNav/StepsNav.stories.js, packages/orion/src/Table/Table.stories.js, packages/orion/src/Tooltip/Tooltip.stories.js, packages/orion/src/Wizard/Wizard.stories.js
Trocando o formato das stories do storybook para o novo: https://medium.com/storybookjs/component-story-format-66f4c32366df.
Esse novo formato é bem intuitivo e tem umas vantagens de deixar mais fácil de reusar as stories em outros contextos. Além de que, provavelmente, no futuro eles devem depreciar o formato antigo. Então quanto mais cedo trocarmos e seguirmos o formato novo melhor :)
=> chore(storybook): Change to the new story format

packages/orion/components.css, packages/orion/src/Pagination/Pagination.stories.js, packages/orion/src/Pagination/Pagination.test.js, packages/orion/src/Pagination/index.js, packages/orion/src/Pagination/pagination.css
Solves #235 
Eu acho que este componente é tão diferente do [Pagination do Semantic](https://react.semantic-ui.com/addons/pagination/) que achei melhor criar um do zero. O que acham?
Right:
**Updated 07/10/2019 18:30**
Disabled:
OBS 1: O estado disabled não existe no [Invison]( https://projects.invisionapp.com/d/main#/console/17711749/367438886/preview). ~Já mostrei pra Bruno pra ver se vamos dar uma "clareada" no texto também~. **Bruno me pediu pra por a mesma opacidade  do botão, no caso:** `opacity-40`.
OBS 2: Este componente é `controlled` apenas. Vocês acham que faz sentido ele não ser controlled? Pra mim não faz.
OBS 3: Ele não tem os aria attributes como o do Semantic. Acham que eu deveria por?
=> feature(pagination): Add Pagination component

packages/orion/src/Divider/Divider.stories.js, packages/orion/src/Divider/divider.css
Adiciona o estilo do divider vertical.
=> feature(Divider): add the vertical style

packages/atomic-bomb/tailwind.config.js
Adicionei alguns background colors para servir de background para o componente: `<Progress color={...} />`
Ex:
=> feature(bg-colors): Add background colors

packages/atomic-bomb/tailwind.config.js
Esse PR adiciona a cor branca como uma das opções de border color.
Pretendo utilizar quando for fazer esse componentezinho da bolinha de status.
=> feature(tailwind.config): add a white border color

packages/orion/src/Datepicker/datepicker.css, packages/orion/src/Dimmer/Dimmer.stories.js, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Label/label.css, packages/orion/src/Loading/Loading.stories.js, packages/orion/src/RangedDatepicker/rangedDatepicker.css
Ops, removi do Atomic Bomb, mas esqueci de olhar se o Orion estava usando, e estava...
=> fix(negative-margin): Replace tailwind negative margin rules

packages/atomic-bomb/tailwind.config.js, packages/orion/src/Card/card.css
A cor da borda do Card mudou, e estamos precisando de mais tons de cinza pra cor de fundo e de texto.
=> feature(css): Change Card's border color and add colors

packages/orion/src/InfoIcon/InfoIcon.stories.js, packages/orion/src/InfoIcon/index.js
Adicionando `popupProps` para o `InfoIcon`.
Aí eu posso fazer algo assim com o `InfoIcon`:
=> feature(info-icon): Add popupProps prop

packages/atomic-bomb/tailwind.config.js, packages/orion/components.css, packages/orion/src/Checkbox/index.js, packages/orion/src/Radio/Radio.stories.js, packages/orion/src/Radio/index.js, packages/orion/src/Radio/radio.css, packages/orion/src/index.js
Chegou o componente **Radio**! 🎉 https://github.com/inloco/orion/issues/232
**Normal**
**Disabled**
=> feature(radio): Add the "Radio" component

packages/orion/src/Table/table.css
tô alterando o negocinho do sort da tabela pra ser wave-500.
=> feat(table.css): changes sort arrow color

packages/orion/src/Input/input.css
fix na cor do placeholder do input
=> feat(input.css): sets placeholder color

packages/orion/src/Layout/LayoutUserProfile/index.js
Adicionando prop de callback a ser executado ao clicar no menu de Logout.
Será necessário para ações de unsubscribe das Analytics, como do logrocket
=> feat(Layout.UserProfile): add onLogout prop

packages/orion/src/Modal/modal.css, packages/orion/src/Table/table.css
Só alterando o `min-width` do Modal pra 384px.
Solicitado por Bruno.
=> fix(modal): Fix modal width

packages/orion/src/Dropdown/dropdown.css
Fixando o line-height deste componente
=> fix(dropdown): Fix misalignment

packages/orion/src/TagsInput/TagsInput.stories.js, packages/orion/src/TagsInput/index.js
tava tentando controlar esse blur do componente apenas com o `onSearchChange` mas não tô conseguindo. vou ter que colocar essa prop pra resolver o problema por ora.
=> feat(TagsInput): adds selectOnBlur prop

packages/orion/src/TagsInput/index.js
eu sou burra
mas agora vai eu juro
=> fix(TagsInput): adds current value only if there is a value

packages/orion/src/Dropdown/dropdown.css
No meu último PR (https://github.com/inloco/orion/pull/645), acho que acidentalmente eu apaguei um código (porque não me lembro de ter feito de próposito), e agora tô corrigindo, porque gerou efeitos colaterais 😞
=> fix(dropdown): Max width

packages/atomic-bomb/tailwind.config.js
Espamos precisando desta cor (space-600) no inloco-frontend.
O resto foi o prettier 👀
=> feat(tailwind): add space-600 for backgroundColor

packages/orion/src/Search/Search.stories.js, packages/orion/src/Search/search.css
=> Feature: add description styling on Search

packages/orion/src/Card/Card.stories.js, packages/orion/src/Card/card.css, packages/orion/src/Card/index.js, packages/orion/src/Card/index.tsx
Aproveitei também pra transformar o Card em typescript 🕺
=> Feature(Card): Add readOnly and disabled states

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/DropdownItem/dropdown-item.css, packages/orion/src/Dropdown/DropdownItem/index.js
Bruno pediu pra mudar a ordem da imagem e checkbox no Dropdown Item.
Antes:
Depois:
Além disso, setei alguns CSS para imagens dentro do dropdown, a pedido de Bruno.
=> fix(dropdown): Fix dropdown checkbox order

packages/orion/src/Wizard/index.js
tava apitando no frontend pro caso que pode colocar descrição no wizard
=> feat(Wizard): adds object as proptype for steps

packages/atomic-bomb/css/base.css, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Input/input.css
[Discussão no Slack](https://inlocoglobal.slack.com/archives/GR41VF11U/p1594998160058600).
Além disso, removi as regras redundantes de placeholders em outros lugares.
=> Fix: change placeholder color to gray-700

packages/atomic-bomb/tailwind.config.js
É a cor a ser usada em um dos charts do incognia, e Cristiano disse que é provavel que usemos novamente no futuro.
=> feat(tailwind): add bg-chart-purple-80

packages/orion/src/StatusTag/index.js
Estamos recebendo erro de proptypes no front-end pq estamos usando o tamanho 'large' mas as propTypes aqui nao estão atualizadas
=> fix(StatusTag): fix prop types

packages/atomic-bomb/tailwind.config.js
Corzinha pra usar nessa Tag do mapa das Demos:
=> feat(atomic-bomb): add background-color space-700-48

packages/orion/src/NotificationCenter/index.js
fui buscar aquela ~~~inspiração~~~ aqui e percebi esse pequeno typo 😸
=> fix(NotificationCenter): fixes NotificationTypes typo

packages/orion/src/StepsNav/stepsNav.css
=> feature(wizard-steps): Change steps color

packages/orion/src/Menu/Menu.stories.js, packages/orion/src/Menu/menu.css
=> feature(Menu): add vertical menu

packages/orion/src/Layout/layout.css
Ajustei o espaçamentos, bordas e cores do Layout.
=> git Fix/layout space colors

packages/orion/src/Layout/Layout.js, packages/orion/src/Layout/Layout.stories.js, packages/orion/src/Layout/layout.css
Adicionando a possibilidade de não ter Sidebar no Layout. Por default ele é `true`
=> feature(layout): Layout without sidebar

packages/orion/src/Layout/layout.css
Cristiano pediu pra dar umas ajustadas no espaçamento do sidebar... Ficou assim:
=> fix(sidebar): Fix styles
