components/Button/index.js
Semantic's icon prop frequently throws warnings for us because it expects icon names from a certain icon library, but we use another. The way out has been to pass the icon as a class name instead of just the icon's name, but that's annoying.
Since we're overriding these components now, it's our chance to automatically do this transformation from icon name to `{ className: iconName }`, hiding this from Orion's users.
=> fix(button): Normalize Button's icon prop

package.json, tasks/build/tailwind.js, yarn.lock
This gulp-plumber npm package swallows the errors and just outputs them on the screen. The developer won't have to run the watch process again, just fix the error as usual.
=> chore(watch): Stop breaking watch due to errors on CSS files

components/Button/button.css, components/Button/index.js, components/Wizard/Footer/BasicControls.js, components/Wizard/Footer/__tests__/WizardFooterBasicControls.test.js, components/Wizard/Footer/__tests__/__snapshots__/WizardFooterBasicControls.test.js.snap, stories/Layout/index.stories.js
I noticed that buttons inside Layout were still the old ones.
Layout is still going to change, so I wasn't going to fix these, but I realized it surfaced some small bugs in the new button, so I ended up fixing everything:
- Changed Layout to start using the new button
- Fixed button props to the new format
- Stopped using `Button.create` from semantic (our Button doesn't have it) and switched it with just simple logic instead.
- Made small fixes to Button: made it be secondary by default, as well as inline (instead of block).
**Before**
**After**
=> fix(layout): Fix buttons inside Layout

.storybook/preview-head.html, README.md, src/Button/index.js, src/Checkbox/checkbox.css, src/Icon/Icon.stories.js, src/Icon/index.js, src/Input/index.js, src/Label/index.js, src/index.js, src/utils/factories.js
Nada mudou visualmente, só estou consertando o componente `Icon` agora que tiramos o CSS do semantic UI do projeto.
Vamos passar a usar o Material Icons direto da CDN da Google:
- É a forma recomendada pelo Material.
- É melhor pra performance, todo mundo bate nessa CDN.
- Teremos sempre os ícones mais atualizados (isso fazia falta, perdíamos de usar alguns mais novos).
- Única desvantagem: os projetos têm que adicionar o `<link>` pra essa CDN manualmente, não virá já com o css do Orion. Mas vale a pena essa config extra e adicionei isso no README.md.
=>  feature(icons): Style Icon

src/Dropdown/Dropdown.stories.js, src/Dropdown/index.js, src/Input/Input.stories.js, src/Input/index.js, src/Input/input.css
Esquecemos dessa flag `fluid`, ela é bastante útil nesses fields. Adicionei a input e dropdown.
**Regular input/dropdown**
**Fluid input/dropdown**
=>  feature(inputAndDropdown): Style fluid input and dropdown

src/Dropdown/dropdown.css
I've styled the multiple dropdown and the search dropdown separately. But I've noticed that when they're both enabled, we need some extra CSS rules.
=> feature(dropdown): Style multiple dropdown with search

src/Input/index.js, src/Input/input.css
Já que adicionar a classe diretamente no componente adiciona `!important` e a gente não quer este comportamento no Orion, estou movendo as classes do componente para o CSS no input, além de remover o `orion-input`.
=> refactor(input): move classes from component to css. Remove orion-input

gulpfile.js, package.json, yarn.lock
We'll have images (such as In Loco's logo) in an assets folder, so we need it to be in the `dist` folder together with our built files.
Also moved the whole build process do gulp. Since part of it was already there it's best to have it all there. It'll be faster (running in parallel) and more organized.
=> chore(build): Copy assets to dist folder when building project

src/Message/Message.stories.js, src/Message/index.js, src/Message/message.css
Adicionando os ícone de dismiss aqui.
Tentei usar o próprio ícone que o Semantic injeta, alterando o CSS, mas não consegui.
Acabei adicionando o ícone usando um wrapper, como @mairatma havia falado no PR anterior.
=> feature(dismissible-message): Add dismissible icon

src/Form/Field/field.css
Victor me falou que conversou com Bruno, e eles concordaram que o placeholder poderia aparecer no Input / Dropdown quando ele estivesse com Focus:
=> feature(placeholder): Show placeholder on focus

package.json, src/ClickOutside/index.js, src/Filter/Filter.test.js, src/Filter/filter.css, src/Filter/index.js
Interações de teclado no componente `Filter`. Agora é possível:
- Dar focus no filtro pelo teclado, e pressionar **Enter/Space** pra abrí-lo.
- Dar **Enter** em um campo dentro do filtro (ex.: input) faz o mesmo que clicar em `Apply`.
- Dar **Esc** em qualquer elemento do filtro faz o mesmo que clicar fora (que é o mesmo que clicar em `Apply` - mesmo comportamento do Airbnb, confirmei com Bruno/Cristiano).
- Usar **Tab** pra se movimentar entre os campos e botões dentro do filtro, e pressioná-los com **Enter/Space.**
**Entrando no filtro pelo teclado e usando Enter pra aplicar o resultado:**
**Entrando no filtro pelo teclado e usando Enter pra pressionar o botão Clear:**
=>  feature(filter): Add keyboard interactions

src/Dropdown/DropdownKeepSelected/index.js, src/Dropdown/index.js, src/Dropdown/useInlineMenuWrapper.js
Desculpem pelo tamanho do texto, não é trivial de explicar e eu queria deixar essa solução clara pra quem for revisar.
O dropdown do Semantic usa `position: absolute` no seu menu. Nada mais justo.
Porém, no Orion nós temos a opção de ter esse menu **inline**, com a nova prop `inlineMenu`. Nesse caso a gente não quer o menu dentro de uma caixinha popup que aparece por cima de qualquer conteúdo. Queremos os itens do menu diretamente abaixo do trigger do dropdown, tomando espaço normalmente, empurrando qualquer conteúdo abaixo dele, ou seja: `position: static`.
Infelizmente não podemos simplesmente torná-lo **static** por conta de como os outros elementos do dropdown (trigger, input, labels, etc) são renderizados.
Quebrei bastante a cabeça procurando uma solução aceitável pra esse caso. …
=> fix(dropdown): Fix inline menu not having the expected height

package.json, src/Checkbox/checkbox.css, src/Dropdown/dropdown.css, src/Input/input.css, yarn.lock
@mairatma Bruno mudou de idéia, veio aqui na mesa, e disse que era melhor que o focus = active.
Expliquei a ele da questão do checkbox, mas ele mesmo assim achou melhor.
Também revisei com ele a quantidade de opacidade no hover para os estados de warning e error, e aumentamos um pouco. Fiz isto direto no atomic-bomb.
=> fix(box-shadow): Make focus = active

src/Checkbox/Checkbox.stories.js, src/Checkbox/checkbox.css
Uns estilos novos pra `label` no atomic bomb afetaram o checkbox. Consertei aqui e aproveitei pra adicionar o espaçamento default entre checkboxes, que estava faltando.
**Antes**
**Depois**
=>  fix(checkbox): Fix checkbox styles and add space between checkboxes

src/NotificationCenter/index.js
Essas keys da prop `defaults` também aceitam outros tipos, como string. Estava dando warning quando usada assim.
Pra evitar copiar a lógica toda do semantic pra cada key dessas, podemos deixar cada uma como `any`. O semantic vai fazer a validação necessária pra cada uma, a gente só precisa detalhar que essas são as keys aceitas na prop `defaults`.
=> fix(notificationCenter): Fix prop types warnings when strings are given

packages/orion/src/Layout/LayoutCenter/index.js, packages/orion/src/Layout/LayoutMain/index.js, packages/orion/src/Layout/LayoutTopbar/index.js, packages/orion/src/Layout/index.js, packages/orion/src/Layout/layout.css
A lógica de centralização do Layout da gente não é tão trivial (margin mínima, width máximo, centralizado, etc) e já estava duplicada em dois lugares (`Layout.Main` e `Layout.Topbar`). Agora vou precisar da mesma lógica novamente pra um header especial lá no `inloco-frontend`, então achei melhor aproveitar pra criar um componente que abstraia essa lógica. Estou chamando ele de `Layout.Center`.
Nada mudou visualmente, só extraí essa lógica e estou exportando esse novo componente.
=> feature(layout): Add Layout.Center component

packages/orion/src/Button/button.css
Adicionando `min-width` para o botão. Alinhado com o time de design.
=> layout(button): Add min-width to the button

packages/orion/src/Button/button.css, packages/orion/src/Filter/filter.css
O botão subtle não deve ter nenhum padding, pois ele é praticamente um link. O padding, herdado dos outros botões, estava atrapalhando o espaçamento em Filter. 
**Antes - Button subtle**
**Depois - Button subtle**
**Antes - Filter**
**Depois - Filter**
=> fix(buttonAndFilter): Fix spacings for filters and subtle buttons

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/index.js
Vamos ignorar acentos no search do dropdown automaticamente. É fácil esquecer de ligar essa prop, ou até mesmo saber que ela existe (experiência própria no 4apps).
**Antes:**
**Depois:**
=> feature(dropdown): Enable deburr by default

packages/orion/src/Dropdown/dropdown.css
A gente quer as labels de dropdowns múltiplos mais próximas da parte esquerda do dropdown do que o input normalmente ficaria.
Eu achei que tinha resolvido isso só adicionando margin negativa pra a primeira label. Mas isso não resolve o caso em que temos muitas labels, formando um dropdown com múltiplas linhas. A partir da segunda linha as labels estavam fora do lugar novamente.
Corrigi agora colocando a margin negativa em todas as labels, com uma margin-right maior pra compensar no espaçamento entre labels.
**Antes:**
**Depois:**
=> fix(dropdown): Fix left spacing for multiple dropdown labels

packages/orion/src/Dropdown/dropdown.css
Revisando com Bruno este dropdown, ele me disse que o height do dropdown small deveria ser 24px em vez de 32px.
Antes:
Depois:
=> fix(Dropdown): height 24px instead of 32px for small size

packages/orion/src/Filter/Filter.test.js, packages/orion/src/Filter/index.js
O valor passado para o conteúdo do `Filter` é sempre o `localValue`.
O valor que é mostrado no trigger é o valor atualmente selecionado, `value`.
Notei um bug que ocorre caso esse valor selecionado seja mudado por fora do filtro (modificado por algum pai, que repassa o novo valor pela prop `value`, por exemplo). Nesse caso, o texto do botão era modificado corretamente, porém o conteúdo do filtro continuava usando `localValue`, e perdia essa atualização.
Corrigi isso nesse pr da seguinte forma: ao abrir o filtro, sempre resetamos o `localValue` para o `value` atual. Assim o conteúdo sempre terá o valor atualizado.
**Antes**
**Depois**
=> fix(filter): Reset local value when opening the filter

packages/orion/package.json, packages/orion/src/Datepicker/index.js, packages/orion/src/RangedDatepicker/RangedDatepicker.stories.js, packages/orion/src/RangedDatepicker/index.js, packages/orion/src/utils/datetime.js, yarn.lock
Os componentes do `react-dates` só aceitam objetos do Moment nas props de datas. Não aceitam strings nem timestamps.
Estou adicionando uma conversão automática pra o moment em nossos wrappers. Já precisei em alguns momentos, isso vai ajudar bastante.
=> feature(datepicker): Automatically convert given dates to moment objects

packages/orion/src/Loading/Loading.stories.js, packages/orion/src/Loading/index.js, packages/orion/src/Loading/loading.css
Estávamos sempre deixando o componente `Loading` inline, mas frequentemente vamos querê-lo centralizado no pai. Deixei esse comportamento como o default e adicionei uma prop `inline` pra o comportamento anterior.
Como ninguém (acredito) ainda usava, é tranquilo mudar esse comportamento default, e achei que a prop ficou mais clara sendo a de `inline`.
=> feature(loading): Add prop for determining if the loader is inline or not

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/Filter.test.js, packages/orion/src/Filter/index.js
Não podemos reusar apenas essas funções do `Popup` do semantic, pois elas não funcionam bem no caso do `Filter` (que usa o `Popup` com a prop `open` como controlled).
=> feature(filter): Add onOpen and onClose props to Filter

packages/orion/src/index.js
Solves #165 .
* feat(packages/orion/src/index.js): change exporting all modules to exporting only overriden modules
=> Stop exporting componentes from `semantic-ui-react` that we haven't styled yet 

packages/orion/src/Button/button.css
Como nossos custom icons não são fontes, as classes css `text-` não funcionam pra trocar a cor deles, como estávamos usando no botão.
Precisamos de regras extras no botão pra usar a cor correta quando o ícone é SVG.
Exemplo:
**Antes**
**Depois**
=> fix(button): Fix color of custom icons inside buttons

packages/orion/src/Menu/menu.css, packages/orion/src/Menu/switcher.css
Como nossos custom icons não são fontes, as classes css text- não funcionam pra trocar a cor deles, como estávamos usando no menu.
Precisamos de regras extras no botão pra usar a cor correta quando o ícone é SVG.
Exemplo (eu sei que é quase imperceptível, mas não para um designer 😆):
**Antes**
**Depois**
=> fix(menu): Fix color of custom icons inside menu items

packages/orion/src/Button/Button.stories.js, packages/orion/src/Button/button.css
Conversei com Bruno hoje, e a idéia é que os botões `subtle icon` tenham um background no hover / active:
Antes:
Depois:
=> style(button): Restyle icon subtle button

packages/orion/src/Menu/menu.css, packages/orion/src/Menu/switcher.css
Os menu items não tinham hover/active states ainda e estavam com a cor errada nos ícones.
**Antes (cor do ícone)**
**Depois (cor do ícone)**
=> feature(menu): Fix icon color and focus/active states

packages/atomic-bomb/tailwind.config.js, packages/orion/src/Card/card.css
Notei que estávamos usando `62, 73, 101` em dois box-shadows da gente, que era o antigo `n600`. Essa cor não existe mais na nossa paleta, então confirmei com Bruno que ela estava errada, deveria ser `61, 62, 63` (nosso `gray-900`), como nos nossos outros box-shadows.
Corrigi isso e aproveitei pra trocar o `shadow-100` dos nossos cards por uma borda normal, agora que a cor está em nossa paleta. A borda dá o mesmo efeito e é mais versátil (não causa problemas de overflow como box-shadow causa, e permite colocar outro box-shadow por cima mais facilmente).
=> fix(color): Fix the color used in box-shadow

packages/atomic-bomb/tailwind.config.js, packages/orion/src/Dimmer/dimmer.css
Eu havia feito o dimmer usando a regra `opacity` pra deixá-lo transparente, mas não percebi que isso iria deixar qualquer conteúdo dele, mesmo com `position: absolute`, transparente também. É o caso do modal, que estava mostrando conteúdo por trás dele.
Troquei o `opacity` por `background-color` já em `rgba` e agora o modal é fosco como esperado, apenas o dimmer tendo transparência.
**Antes**
**Depois**
=> fix(dimmer): Fix dimmer's background color

packages/orion/src/Dropdown/DropdownItem/dropdown-item.css
Quando usamos `<Dropdown.Item as={Link} />`, o layout quebra porque `<a>` é um elemento inline. 
Adicionando um `display: block` resolve nosso problema:
=> fix(dropdown-item): Fix dropdown item as link

packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/TableCell/index.js, packages/orion/src/Table/TableHeaderCell/index.js, packages/orion/src/Table/constants.js, packages/orion/src/Table/table.css
Ao invés de determinar o height de cada row/column indiretamente através do fontsize + padding, estou definindo o height de forma mais fixa aqui e centralizando verticalmente o conteúdo.
Por enquanto queremos de fato que essas linhas não fiquem mais altas que isso (tanto que adicionei o `truncate` no último pr), então não precisamos de flexibilidade nessa altura. Pelo contrário, queremos que seja sempre igual.
E usando padding não estava sendo possível ter conteúdo maior do que apenas texto em cada coluna, causando problemas como no screenshot abaixo (esse foi o motivo principal pra fazer o pr na verdade):
**Antes**
**Depois**
=> feature(table): Remove vertical padding from table cells

packages/orion/src/Dropdown/dropdown.css
Só adicionamos padding horizontal quando o Dropdown é um selection:
Antes:
Depois:
=> fix(dropdown): Add padding only when it is a selection

packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/TableCell/index.js, packages/orion/src/Table/table.css
Nos dois lugares do Invision em que eu tinha visto o nosso uso de `highlight` pra table headers, me pareceu que nós não estávamos fazendo o highlight na célula inteira, mas apenas ao redor do tamanho do conteúdo. Por isso fiz o highlight em um elemento `inline-block` com padding.
Porém, notei que isso causa problemas porque o conteúdo de células da mesma coluna pode variar de tamanho, e então o highlight variava também e ficava esquisito. Olhando melhor o Invision, notei que na verdade as duas telas estavam usando width fixo pra essa área do highlight, ao invés de ser sempre o tamanho do conteúdo.
Ou seja, o uso do highlight pode variar de tabela em tabela, e deixando o elemento com `inline-block` forçava esses usos a sobrescreverem mais CSS do que se apenas adicionassem o highlight …
=> feature(table): Change highlight feature to highlight the whole cell

packages/atomic-bomb/tailwind.config.js, packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/table.css
Estilizei nossa `Table` para quando ela é **sortable**. Lembrando que é só o estilo mesmo, o funcionamento não é implementado automaticamente pelo semantic (e é realmente complicado deixar genérico pra a maioria dos casos, estou achando melhor ter um hook pra ajudar com isso, provavelmente no repo do produto mesmo).
=> feature(table): Style the sortable table

packages/orion/src/Table/TableCell/index.js, packages/orion/src/Table/table.css
Ontem eu fiz um pr que simplificava nossa feature de highlight, deixando ela sempre cobrindo a célula inteira ao invés de tentar cobrir só o seu conteúdo. E em casos especiais, quem chama `Table` poderia fazer seu próprio highlight cobrindo o conteúdo que interessar.
A idéia é justamente essa, mas a execução não ficou perfeita. Isso porque eu precisei manter o `inner-cell-wrapper` por conta da lógica de text truncation (não dá pra fazer o truncation com um pai flex se o filho for texto puro, então eu mantive esse wrapper pra o pai sempre ter um filho e o caso mais comum já funcionar com text truncation).
Esse `inner-cell-wrapper` não estava cobrindo o width e o height inteiro da célula, porque seu pai era `flex` e estava posicionando ele. Isso impossibilita que a pessoa usando `Table` …
=> fix(table): Change Table to easily allow custom cell content (like custom highlights)

packages/orion/src/Icon/index.js, packages/orion/src/Input/index.js, packages/orion/src/Label/index.js, packages/orion/src/Message/index.js, packages/orion/src/Table/TableCell/index.js
O semantic ui tem essas factories em alguns componentes, que são bastante úteis pra criar props de shorthands e também são usadas internamente pelo próprio semantic. É importante que todo componente que a gente sobrescrever e tiver factories no semantic continue tendo também.
Notei que alguns estavam faltando (ou sobrescrever ou referenciar), então corrigi isso aqui.
=> fix(factories): Add missing factories from semantic ui to the components we're wrapping

packages/orion/src/Card/card.css
Para cards que não têm height auto, caso sobre height ele estava sendo acrescentado depois do footer. Ajeitei pra esse espaço extra ir todo para o conteúdo principal.
**Antes**
**Depois**
=> fix(card): Make the card content fill any extra available space instead of the footer

packages/orion/src/Popup/popup.css
Como não definimos nenhum `width` ou `max-width` para a nossa `Popup`, ela cresce com o conteúdo. Com um conteúdo muito longo isso atrapalha o hover, pois ela fica grande demais e por cima do trigger.
Notei que o semantic tinha um `max-width` na popup, e nos nossos exemplos no Invision também existia um limite. Então achei uma boa acrescentar um limite padrão logo aqui.
**Antes**
**Depois**
=> feature(popup): Limit the popup's width

packages/orion/src/Table/table.css
O alinhamento da setinha pra ordenação estava errado. Não notei porque fica ok com o alinhamento padrão à esquerda, mas ficava visível ao centralizar ou alinhar à direita.
**Antes**
**Depois**
=> fix(table): Fix alignment of sorting arrow

packages/orion/src/Filter/Filter.test.js, packages/orion/src/Filter/index.js
Eu implementei o botão `Clear` como se fosse um `Cancel`, sempre restaurando o valor para o último valor aplicado. Bruno me explicou que na verdade era pra esse botão realmente dar um clear geral na seleção, deixando-a vazia, e não restaurando a última. Agora está corrigido.
=> fix(filter): Fix behavior of the "Clear" filter button

packages/orion/src/Wizard/wizard.css
O StepsNav tinha ficado sem o margin-bottom de 40px.
=> feature(Wizard): add a bottom margin to the StepsNav

packages/atomic-bomb/tailwind.config.js
Precisei dessas cores e notei que:
- A space-50 estava errada (estava um rosinha...) 😱 
- A space-500 não estava nem em cor de texto nem background, e vou precisar nos dois lugares. Faz sentido ela estar neles até, pois é a cor principal da paleta space.
=> fix(colors): Fix wrong color and add another as text and background color

packages/orion/src/Button/button.css
Falei com Bruno e Victor, e eles disseram que este botão ghost deveria ter background `transparent` em vez de `white`.
Antes:
Depois:
=> fix(button-ghost): Set bg transparent rather than white

packages/orion/src/Button/Button.stories.js, packages/orion/src/Button/button.css, packages/orion/src/Filter/Filter.stories.js
É bem comum se usar mais de um filtro, mas eles estavam colados um no outro nesse caso. Achei que valia a pena deixar a regra de espaçamento entre filtros já no orion, pra não ficar repetindo em cada uso.
**Antes**
**Depois**
=> feature(filter): Add spacing between filters

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Dropdown/index.js, packages/orion/src/utils/directions.js
Solves https://github.com/inloco/orion/issues/256.
This adds the style needed to set the `direction` prop as `left|right`. By default, Semantic UI sets the direction to be left, so the respective style is not needed.
=> Feature: support for direction prop on Dropdown

packages/atomic-bomb/tailwind.config.js
Adds the `first` and `last` variants to margins. These variants work as `first-child` and `last-child`.
The main use case will be to add margins to a list of components, minus the first/last one.
=> feature(tailwind.config): add the first and last variants to margin

README.md, package.json, packages/orion/src/ClickOutside/index.js, packages/orion/src/Dropdown/index.js, packages/orion/src/Filter/Filter.stories.js, packages/orion/src/RangedDatepicker/index.js
Docs com versões fica bonitinho:
Corrigi os erros e os warnings abaixo dos mesmos arquivos. Ainda tem 51 warnings sobre falta de `propTypes`.
```bash
orion/packages/orion/src/RangedDatepicker/index.js
12:3   warning  'focusedInput' is missing in props validation   react/prop-types
13:3   warning  'onDatesChange' is missing in props validation  react/prop-types
14:3   warning  'onFocusChange' is missing in props validation  react/prop-types
28:36  error    'newDates' is not defined
orion/packages/orion/src/Dropdown/index.js
94:1  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
orion/src/Filter/Filter.stories.js
51:24  error    '_' is not defined                         no-undef
75:29  warning  'onChange' is missing in props validation …
```
=> Refactor: eslint fix

packages/orion/src/StepsNav/index.js, packages/orion/src/StepsNav/stepsNav.css
Corrige as cores do componente `StepsNav`.
Antes:
Depois:
=> feature(StepsNav): update the text and icon colors

packages/orion/src/Loading/index.js
A animação de loading parava se o componente fosse clicado.
Essa prop desabilita esse pause (https://github.com/chenqingspring/react-lottie/issues/81).
=> feature(Loading): disable the animation pause on click

packages/orion/base.css
Na avaliação que Bruno fez do application, ele pediu que as animações em geral tivessem um tempo de 0.15s ao invés de 0.2s, já que achava que tava um pouco lento.
=> feature(base.css): update the default transition duration to 0.15s

packages/orion/src/Message/message.css
O `padding-right` de 4px quando não tinha título deixava o texto bem próximo do ícone.
Esse PR altera o `padding-right` para que a distância do ícone seja igual ao padding do `Message`.
Antes:
Depois:
=> feature(Message): change the icon padding to 16

packages/orion/src/FullscreenContainer/fullscreenContainer.css
Bruno pediu para diminuir o conteúdo do Fullscreen Container para 768px.
Com 1024px
Com 768px
=> feature(FullscreenContainer): change the max-width to 768px

packages/orion/src/StepsNav/stepsNav.css
O texto estava alinhado à esquerda, o que era um problema quando tinha quebra de linha. 
Antes
Depois
=> feature(StepsNav): add text-center

packages/atomic-bomb/tailwind.config.js
Removendo a margem negativa, conseguimos diminuir o bundle de 38kb para 34kb (gziped) do Atomic bomb.
=> chore(negative-margin): Remove negative margin

packages/orion/src/StatusTag/StatusTag.stories.js, packages/orion/src/StatusTag/index.js
Como @mairatma havia sugerido, configuro `Types` como um atributo de `StatusTag`. Dessa forma, o dev pode acessá-lo apenas importando `StatusTag`.
=> Refactor: export types as an attribute of StatusTag

packages/orion/src/StatusTag/StatusTag.stories.js, packages/orion/src/StatusTag/index.js, packages/orion/src/StatusTag/statusTag.css
Como sugerido por @marcelscr , esses nomes se encaixam mais no padrão.
=> Refactor: rename StatusTag types

packages/orion/src/Dropdown/index.js
No momento é impossível passar `ref` para **Dropdown** porque ele é um function component. O componente original do semantic ui podia receber `ref` normalmente por ser uma classe, e realmente isso é importante pois pode ser necessário acessar os elementos do dropdown (para ouvir o scroll, por exemplo).
Pra fazer isso funcionar com um function component basta usar `React.fowardRef` para poder indicar a que elemento o `ref` vai se associa. Foi apenas isso que fiz aqui.
=> feature(dropdown): Allow passing ref to "Dropdown"

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/Dropdown.test.js, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Dropdown/index.js
Às vezes queremos um multiple dropdown que não mostre as opções selecionadas em labels. 
Temos um caso agora no produto em que quase todas as opções possuem o mesmo nome, sendo distinguidas por endereço, então seria esquisito mostrar as seleções todas com o mesmo nome.  Mostrar os endereços selecionados no lugar dos nomes seria muito grande também.
Outro caso é quando podem haver muitas seleções, pois as labels ocupam bastante espaço. E a gente já consegue mostrar as opções selecionadas no próprio dropdown menu, então essa informação não fica faltando.
Infelizmente o semantic ui não tem a opção de não renderizar as labels, então adicionei uma prop pra isso e estou escondendo-as pelo CSS.
**Antes**
**Depois**
=> feature(dropdown): Add prop for hiding selected labels on the multiple dropdown

packages/orion/src/Dropdown/DropdownKeepSelected/index.js
É a mesma idéia de https://github.com/inloco/orion/pull/372, mas lá faltou eu repassar o `ref` quando a opção de manter os itens selecionados no dropdown é ativada. Nesse caso eu uso outro function component pra isolar a lógica relacionada a essa feature, então ele precisa receber o `ref` também para repassar ao `Dropdown` do semantic ui.
=> feature(refs): Add missing ref to dropdown

packages/orion/src/Button/button.css, packages/orion/src/Filter/filter.css
O estilo do botão do `Filter` mudou um pouco, pra ficar mais arredondado. Mudou também a cor usada quando ele está aberto.
**Antes**
**Depois**
=> feature(filter): Make filter trigger buttons more round

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/Filter.test.js, packages/orion/src/Filter/FilterClearIcon/index.js, packages/orion/src/Filter/filter.css, packages/orion/src/Filter/index.js
Um `x` agora aparecerá quando houver algum valor selecionado no `Filter`. Clicando nele o filtro é automaticamente zerado.
=> feature(filter): Add a cancel button for clearing the value without opening the filter

packages/orion/src/Button/Button.stories.js, packages/orion/src/Button/button.css, packages/orion/src/Button/index.js, packages/orion/src/Filter/filter.css, packages/orion/src/Filter/index.js
O componente `Filter` usa buttons mas com um tamanho menor. Ele mesmo estava dando override no button para conseguir isso. Mas acredito que faça mais sentido `Button` ter uma prop para controlar melhor esses tamanhos, como já temos para outros componentes. Da mesma forma que pra os outros, ele só tem duas opções de tamanho: **default** e **small**.
=> feature(button): Add "size" prop to `Button`

packages/orion/src/FilterBar/index.js
Da forma que eu fiz o código, se a cada vez que `FilterBar` fosse renderizado com alguma prop nova, a gente repassasse um objeto `value` novo, o local value era atualizado com este objeto.
Isso causa bugs frequentemente, pois é comum passar `value` sempre como um novo objeto por conta de concatenações spread, mesmo que o resultado final seja igual ao `value` anterior. Nesse caso não era pra local value mudar, pois ele perde o valor pendente e fica voltando para o valor anterior dos filtros.
Daria pra adaptar o código que estava lá para funcionar, guardando o valor antigo em uma ref e checando se o novo valor é realmente diferente, mas isso deixa o código mais complexo e não tem necessidade. Troquei por algo mais simples e correto.
=> fix(filterBar): Fix different references of the same `value` reseting the local value

.circleci/config.yml, .gitignore
Agora o lint pode rodar a cada build da gente pra detectar os erros.
Aproveita pra tentar corrigir o skip de gh-pages também. Hoje o job sempre falha quando é pra esse branch, porque o código que vai pra lá é diferente mesmo, não inclui os testes. Já tínhamos configuração pra ignorar isso, mas ela não funcionava. Parece que só dá pra ignorar branches em workflows, mas não em jobs.
=> chore(circleci): Add lint checks and skip gh-pages

packages/orion/src/Message/Message.stories.js, packages/orion/src/Message/index.js, packages/orion/src/Message/message.css
Adicionei a possibilidade do component Message ter esse estilo Info, pois será utilizado na página de Competidores
Como será utilizado:
Imagens: 
y6
=> feat(Message): Add info option

packages/orion/src/Icon/index.js
Existe uma PropType melhor pra esse caso de uso: `PropTypes.elementType`. Eu nem conhecia, mas notei que quando passamos um componente SVG pra essa prop ela dá warning no 4apps, apesar de funcionar no componente. Então vi que no semantic ui eles usam esse tipo e realmente isso faz o warning sumir. Então corrigi aqui.
=> chore(prop-types): Fix type of "as" prop in "Icon"

packages/orion/src/Dropdown/index.js
Essas props são `true` por default no semantic, mas causam um comportamento muuuito esquisito que nós estamos sempre desabilitando ao usar o `Dropdown` na In Loco.
`selectOnBlur` faz com que o primeiro elemento do `Dropdown` seja selecionado assim que ele é aberto, mesmo que ninguém clique nele. Então se a pessoa apenas abrir e fechar sem fazer nada, o primeiro elemento é selecionado por default.
`selectOnNavigation` faz com que os elementos sejam selecionados ao passar por eles com as setas do teclado, mesmo que o usuário nunca aperte enter nem selecione de fato. 
Ambos fazem muito mais sentido como `false` por default, e como estamos sempre tendo que fazer isso mesmo eu acho uma boa aproveitar pra deixar assim no Orion.
**Antes**
**Depois**
=> feature(dropdown): Make "selectOnBlur" and "selectOnNavigation" props from Dropdown be false by default

packages/orion/src/Menu/index.js
Eu notei esse warning do React agora no storybook do `Menu`, reclamando da prop `size`.
Isso é só uma besteira que eu esqueci de avisar ao revisar o pr https://github.com/inloco/orion/pull/442. Basicamente é porque o semantic tem 6 definições de `size` (como dá pra ver no warning que eles lançam abaixo), mas a gente só usa 2: **small** e **default**. Ao invés de permitir passar qualquer valor do semantic, o que poderia gerar alguma confusão quando não funcionasse, eu achei melhor limitar o nosso lado a apenas esses 2 mesmo. 
Mas pra isso funcionar a gente tem que sempre dar override na prop do componente e repassar pra o `className` manualmente, ignorando os prop types do semantic.
Não fazer isso nem daria erro, mas como eu achei melhor definir o default como vazio, e o semantic não …
=> chore(prop-types): Fix prop types warning on Menu

packages/orion/src/Dialog/Dialog.stories.js, packages/orion/src/Dialog/dialog.css
Eu notei umas diferenças sutis nas cores que estavam sendo usadas para o header de cada tipo de **Dialog**. Ajustei elas aqui.
Também notei que o ícone usado deveria ser diferente pra cada tipo, mas no storybook a gente usava sempre o mesmo. E como já comecei a usar no 4apps achei meio repetitivo ficar adicionando esse ícone na mão, então mudei o **Dialog** pra adicionar automaticamente o ícone correto por CSS.
**Antes (default)**
**Depois (default)**
**Antes (warning)**
**Depois (warning)**
**Antes (danger)**
**Depois (danger)**
=> feature(dialog): Change the color and icons for Dialog

packages/orion/src/Dialog/index.js, packages/orion/src/Dimmer/Dimmer.stories.js, packages/orion/src/Dimmer/dimmer.css, packages/orion/src/Modal/index.js, packages/orion/src/index.js
Bruno me explicou que precisamos de dois tipos de dimmer:
> O branquinho é indicado pra quando for um popup que surja in-context (no caso dos filtros de insights por exemplo) enquanto o escuro ajuda a dar mais destaque a modais/alerts.
Peguei o estilo do dimmer escuro no Invision e aproveitei a prop `inverted` do semantic pra isso. Deixei esse escuro como o default pra `Modal`  e `Dialog`, mas é possível trocar se necessário através da prop `dimmer` que o semantic fornece.
**Antes (Modal)**
**Depois (Modal)**
**Antes (Dialog)**
**Depois (Dialog)**
=> feature(dimmer): Add a darker version of the dimmer and use it for global modals

packages/orion/package.json
Sempre que o processo de deploy faz um commit pra branch `gh-pages`, o circle CI faz um build que falha. Isso acontece pq a branch não tem o arquivo `.circleci/config.yml`.
Encontrei [aqui](https://circleci.com/docs/2.0/skip-build/) que se adicionarmos "[ci skip]" ou "[skip ci]" na mensagem de commmit, o circle-ci vai ignorar aquele commit. 
Então estou atualizando a mensagem do commit que o `storybook-deployer` faz, como descrito aqui:
https://github.com/storybookjs/storybook-deployer#custom-deploy-configuration
=> feat(storybook-deployer): add [ci skip] to storybook commit message

packages/orion/src/Slider/Slider.stories.css, packages/orion/src/Slider/Slider.stories.js, packages/orion/src/Slider/index.js
Notei que quando passava um `className` para o componente de slider, ele perdia os estilos padrões porque o `className` era sobrescrito.
Este PR resolve isso:
Exemplo de customização de cor do track:
=> fix(slider): Fix slider when passing classname

packages/orion/src/Icon/icon.css
Deixei as regras do nosso loading icon mais específica, pra parar de conflitar com outras existentes (como as do supernova antigo, que também usa o semantic por trás e também aplicam regras a `i.icon`).
=> chore(loading): Make the loading icon rules more specific

packages/orion/src/Dropdown/Dropdown.test.js, packages/orion/src/Dropdown/DropdownItem/dropdown-item.css, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Label/index.js, packages/orion/src/Label/label.css, packages/orion/src/Slider/Slider.test.js
Textos grandes estavam saindo pra fora dos componentes. Passei a truncar por default.
**Antes**
**Depois**
**Antes (multiple)**
**Depois (multiple)**
=> feature(dropdown-label): Truncate dropdown and label text

packages/orion/src/Icon/index.js
Eu fiz um pr deixando as regras CSS do `Icon` mais específicas pra o **Orion**, pra não entrar em conflito com outras libs (como o **Supernova**).
Isso funcionou perfeito pra o ícone especial de **loading**, que é um ícone especial. Mas pra os ícones normais eu acabei quebrando uma regra que existia, porque o semantic não adiciona o prefixo do projeto (que no nosso caso é **orion**) pra `Icon`, só para todos os outros componentes. Aí uma regra que eu deixei mais específica (de `i.icon` para `i.orion.icon`), que definia o tamanho da fonte, parou de pegar.
Ajeitei aqui adicionando eu mesma o prefixo, pra podermos ter essas regras mais específicas funcionando.
**Antes (estava pegando fonte 24px do material icons)**
**Depois (com os nossos 20px default)**
=> fix(icon): Fix some Icon CSS rules not being applied

packages/orion/src/Slider/slider.css
Quando o slider está focado, ele adiciona um shadow no `thumb` do slider.
O container do Slider tem um `overflow: hidden` porque a gente tá usando uma técnica de shadow "pintar" o `track` de outra cor do lado esquerdo (apenas no Chrome).
Para que a parte do shadow do track não ficasse hidden quando ele estivesse em algumas das pontas (olhar imagem), eu adicionei um padding de `1px` para os lados. Esta solução funcionou bem no Chrome, mas não no Firefox, que não usa a gambiarra mencionada acima.
Então adicionei um css que só funciona no Firefox, e resolve o problema que só acontece no firefox:
Antes:
Depois:
=> fix(firefox): Fix overflow on Firefox

packages/orion/src/Button/button.css
Nossos botões ficavam esquisitos com ícones, devido ao espaçamento interno do ícone. Ajustei o alinhamento pra ficar melhor.
**Antes**
**Depois**
=> fix(button): Fix alignment of buttons with icons

packages/orion/src/InfoIcon/infoIcon.css
Aquele `.orion` que eu acrescentei nas regras do `Icon` pra torná-las mais específicas quebrou o tamanho do `InfoIcon`, que ficou menos específico do que as regras default agora.
Ajeitei e verifiquei todos os componentes do Orion pra ver se mais algum tinha sido afetado, mas esse parece ter sido o único mesmo (🙏).
**Antes**
**Depois**
=> fix(InfoIcon): Fix InfoIcon's size

packages/orion/src/Button/Button.stories.js, packages/orion/src/Button/button.css, packages/orion/src/Button/index.js
Nosso **Button** ainda não fazia nada caso passássemos a prop **loading**. Agora ele mostra um loading spinner.
**Primary**
**Secondary**
**Ghost**
=> feature(button): Add styles for when a button is loading

packages/orion/src/Checkbox/Checkbox.stories.js, packages/orion/src/Checkbox/checkbox.css
Esse pr traz 3 fixes para o **Checkbox**:
1. O cursor quando o checkbox estava disabled era o **pointer**. Passou agora a ser o **default**.
2. Quando não havia label estávamos deixando o checkbox com uma margenzinha à direita, como se fosse o espaçamento para a label inexistente. Isso faz ele tomar mais espaço do que o que deveria e atrapalha alinhamentos. Era um bug nas regras CSS que um dia funcionaram pra isso, mas falharam quando outras ficaram mais específicas.
**Antes**
**Depois**
3. Quando a label ocupava mais de uma linha, o height do checkbox continuava sendo `16px` mesmo com um conteúdo maior. Ajustei a regra pra definir min height no lugar de height.
**Antes**
**Depois**
=> fix(checkbox): Fix checkbox without label and disabled cursor

packages/orion/src/Input/input.css
Setar um width ou height no **Input** no **Orion** não estava funcionando. O componente se comportava de uma forma esquisita em ambos os casos. Corrigi os dois aqui.
**Antes (com custom width)**
**Depois (com custom width)**
**Antes (com custom height)**
**Depois (com custom height)**
=> fix(input): Fix input height/width not matching the component's height/width

packages/orion/src/Input/index.js, packages/orion/src/utils/factories.js
De vez em quando caio nesse problema: algum componente precisa usar refs em um componente do **Orion** e não funciona porque usamos functional components.
Dessa vez foi o **Input**, aí adicionei o `forwardRef` nele pra pegar direitinho.
Mas depois talvez valha a pena ir de componente em componente adicionando em todos, e deixar na doc um guideline pra gente sempre criar novos componentes já com isso por default.
=> fix(input): Forward refs to the input component

packages/orion/src/Input/Input.stories.js, packages/orion/src/Input/input.css
O **Input** com label faltava ser estilizado, por enquanto ficava bem esquisito. Ajeitei aqui.
**Antes**
**Depois**
=> feature(input): Style labeled inputs

packages/orion/src/Search/Search.stories.js, packages/orion/src/Search/search.css
Haviam 2 problemas com o width do componente **Search**:
1. Se o width do componente fosse setado, o input interno dele não acompanhava esse width, parecendo que nada foi feito:
**Antes**
**Depois**
2. A prop **fluid** não estava fazendo nada. https://github.com/inloco/orion/issues/433
**Antes (com fluid)**
**Depois (com fluid)**
=> fix(search): Fix Search width

packages/orion/src/Form/Field/field.css
A altura dos itens do dropdown estava maior quando o dropdown estava dentro de um form. Era só uma regrinha de CSS que estava afetando os elementos `.text` dentro de cada item, mas deveria afetar apenas o `.text` que fica diretamente dentro do dropdown. Deixei a regra mais específica pra corrigir.
**Antes**
**Depois**
=> fix(form): Fix dropdown items height inside forms

packages/orion/src/Form/Field/field.css, packages/orion/src/Form/Form.stories.js
Em alguns casos queremos os nossos fields inline com a label. Existe um `Form.Group` que ajuda com isso no semantic, mas faltava implementar um CSS **inline** pra ele.
**Normal**
**Inline**
P.S.: Garanti que isso não está afetando as floating labels.
=> feature(field): Allow fields to be inline

packages/orion/src/Datepicker/datepicker.css, packages/orion/src/DatepickerInput/DatepickerInput.stories.js, packages/orion/src/DatepickerInput/SharedInput/index.js, packages/orion/src/DatepickerInput/datepickerInput.css
Não tinha como passar props para a popup do novo **DatepickerInput**, então adicionei essa opção agora com a prop **popupProps**.
O principal caso de uso que me fez notar isso era a posição da popup, então aproveitei pra adicionar uma knob no storybook pra testar essa opção.
**Bottom left (default)**
**Bottom right**
=> feature(datepicker): Allow passing props to the picker's popup

packages/orion/src/DatepickerInput/index.js, packages/orion/src/DatepickerInput/utils.js, packages/orion/src/RangedDatepickerInput/index.js, packages/orion/src/utils/datetime.js
Notei que o **moment** estava lançando warnings no console quando uma data era selecionada no novo **DatepickerInput**:
Pelo visto o **moment** não suporta o formato que estamos usando para as datas (MM/DD/YYYY) automaticamente. Pra aceitá-lo ele tem que receber diretamente o formato sendo usado ao converter para o moment. Então foi o que fiz e o warning sumiu.
=> chore(datepicker): Get rid of warning from "moment"

packages/orion/components.css, packages/orion/src/DatepickerInput/SharedInput/index.js, packages/orion/src/Form/Field/field.css, packages/orion/src/RangedDatepickerInput/RangedDatepickerInput.stories.js, packages/orion/src/RangedDatepickerInput/RangedDatepickerInput.test.js, packages/orion/src/RangedDatepickerInput/index.js, packages/orion/src/RangedDatepickerInput/rangedDatepickerInput.css
Usando o novo **RangedDatepickerInput** eu entendi um motivo importante de o **react-dates** usar 2 inputs (um pra start date e outro pra end date) ao invés de apenas 1. Com 1 input temos apenas um placeholder, o que causa confusão quando uma das datas é opcional, por exemplo. Nós avisávamos que a data era opcional no placeholder dela, por exemplo:
Com apenas 1 input, quando uma das datas é preenchida, mostramos algo assim:
Ficou bem mais difícil entender que a data final seria opcional...
Falei com Bruno e ele achou melhor usarmos 2 inputs mesmo, e me passou o novo visual. Apliquei ele aqui e ficou assim:
=> chore(RangedDatepickerInput): Split the ranged datepicker input into two

packages/orion/src/DatepickerInput/SharedInput/index.js, packages/orion/src/DatepickerInput/datepickerInput.css, packages/orion/src/RangedDatepickerInput/index.js, packages/orion/src/RangedDatepickerInput/rangedDatepickerInput.css
Acredito que esses são os últimos! 🙏
3 fixes:
1. O **disabled** state parou de funcionar pra **RangedDatepickerInput** quando eu quebrei ele em 2 inputs. Ficou assim agora:
2. O valor inicial mostrado pelo **RangedDatepickerInput** também parou de funcionar quando quebrei em 2 inputs.
3. A prop **fluid** não estava funcionando em ambos os datepickers. Ficou assim agora:
=> fix(datepicker): Three fixes for the new datepickers

packages/orion/src/Datepicker/datepicker.css, packages/orion/src/RangedDatepicker/RangedDatepicker.stories.js
Ok, agora sim deve ser o último... 🙏 
Faltava o estilo das datas out of range no datepicker. A gente já tinha esse estilo pra disabled dates, mas a classe usada pra o caso do ranged datepicker era diferente.
=> feature(rangedDatepicker): Style out of range dates

packages/orion/src/Dropdown/dropdown.css
Pequeno fix do problema que comentei la no chapter.
Com a margin negativa, o icone do dropdown acaba ficando fora do bounding box do dropdown:
Entao removi a margin negativa e ficou tudo certo.
@mairatma comentou que essa margin negativa eh por causa da distancia do icone do dropdown de selection. 
Entao, para o de selection, estou setando um padding a direita menor ao inves de usar a margin negativa. E o resultado eh visualmente o mesmo:
=> fix(Dropdown): remove negative icon margin

packages/orion/src/DatepickerInput/DatepickerInput.test.js, packages/orion/src/RangedDatepickerInput/RangedDatepickerInput.test.js
Os componentes de DatePicker abrem por default no mês corrente. 
Os testes desses componentes estavam testando usando valores para o mês de Fevereiro de 2020, então eles estavam funcionando até o último sábado (29/02/2020). Assim que mudou o mês, os resultados selecionados mudaram, então os testes começaram a falhar.
Estou corrigindo fazendo o teste usar sempre o mês corrente (usando `moment()`), e os primeiros dias do calendário para os testes.
=> test(DatepickerInput): use current dates for test cases

packages/atomic-bomb/css/base.css, packages/atomic-bomb/css/font.css, packages/atomic-bomb/tailwind.config.js, packages/orion/src/Icon/icon.css, packages/orion/src/Message/message.css
Seguindo o que foi discutido no canal #orion, eu fiz o upgrade de spec:
Mudanças que impactam o front:
* O tamanho XL da fonte (24px) morreu.
*Update*: Na verdade não morreu, a gente deixou ele pra 20px, porque ele pode ser usado como o tamanho de ícone.
* O tamanho LG (20px) passa a ser 18px e line-height 24px
* Atualização da UI dos alerts (morreram as bordas e ajuste de padding)
Mais info no slack canal #orion.
=> feature(orion): Upgrade Spec

packages/orion/src/Layout/LayoutUserProfile/index.js, packages/orion/src/Layout/LayoutUserProfile/layoutUserProfile.css
Pequenos fixes no componente de User Profile.
1. A div dos textos estava com o display default (block), daí tinha um espaço entre as linhas que deixava a caixa maior do que deveria ser (o tamanho correto é  42px, ela estava com 48px)
2. O hover e o active estavam com a mesma cor. Na vdd, o active precisa ter uma opacidade de valor maior, para ficar mais escuro.
3. A cor do ícone da setinha não estava setada.
GIF com antes e depois
=> fix(LayoutUserProfile): fix dimensions and colors

packages/orion/src/Layout/LayoutUserProfile/index.js, packages/orion/src/Layout/LayoutUserProfile/layoutUserProfile.css
Adicionando uma altura máxima para o menu de userProfile. Victinho definiu com um limite máximo de 6 itens no menu.
=> feat(LayoutUserProfile): set maxHeight to userProfile

packages/orion/src/Wizard/Wizard.stories.js, packages/orion/src/Wizard/WizardControls/index.js
Bruno pediu pra eu fazer uns ajustes no Wizard...
1. Adicionamos o botão de `Cancel`, não obrigatório.
2. Movemos o botão de `Back` para o lado direito, junto do `Next`.
3. Movemos o botão de `Save` para a esquerda, junto do `Cancel`.
4. O botão `Save` estava como ghost, mas deveria ser o cinza.
Resultado:
=> feature(wizard): Add Cancel button and change button's position

packages/orion/src/Form/Field/field.css
O conteudo dos inputs de um Form têm um padding-top para dar espaço à label que sobe para o topo do input. O problema é que se a label não estiver presente, o padding continua lá e fica desalinhado:
Então estou especificando a regra que traz esse comportamento para atuar apenas se a `label` estiver vazia, ficando centralizado caso aconteça
=> fix(Form.Field): apply top pading only if label is not empty

packages/orion/src/Layout/LayoutAppsDropdown/index.js
No meu ultimo PR nao testei bem o AppsDropdown e acabei deixando um bug que faz o Tooltip aparecer quando o cursor vai pro  menu aberto. Isso acontece pq coloquei o Tooltip em todo o componente. 
Estou mudando para adicionar  o tooltip apenas no `Icon` usado como trigger pro Dropdown.
=> fix(LayoutAppsDropdown): add Tooltip to icon instead of whole dropdown

packages/orion/src/Layout/layout.css
Victinho atualizou o estilo do Dropdown de troca de produtos. Houveram mudancas na cor do bg das imagens e a remocao do "padding" no hover dos itens
Antes era assim
Atualizei para ficar assim:
=> feat(Layout): update apps-dropdown style

packages/orion/src/Wizard/wizard.css
Outro ajuste solicitado por Bruno.
Aumentar a distância entre o conteúdo do wizard e os botões.
Antes:
Depois:
Visão geral:
=> fix(wizard-controls): Increase distance between content and controls

packages/orion/src/Form/Field/field.css
A distância entre o label e o campos estava em 4px mas agora é 8px.
Alinhado com Bruno.
Antes:
Depois:
=> fix(field-label): Fix distance between Label and field

packages/orion/src/Dimmer/dimmer.css
Corrige a issue https://github.com/inloco/orion/issues/581
O dimmer não estava previnindo o scroll do componente abaixo.
=> fix(Dimmer): prevent dimmable components from scrolling

packages/atomic-bomb/tailwind.config.js
Hoje quando a quer fazer esta funcionalidade:
A gente pode fazer via React setando states no `onMouseOver` e `onMouseOut`.
Ou usando CSS:
```html
<tr className="tr">
<td>
<div className="actions">... buttons ...</div>
```
-------
```css
.actions { display: none }
tr:hover .actions { display: block }
```
A solução CSS quase sempre é a melhor, porque não precisa re-render, ou seja, mais performática.
Acontece que o tailwind tem o `group-hover`, que serve exatamente pra isso:
```html
<tr className="group">
<td>
<div className="hidden group-hover:block">
```
Mas pra isso a gente precisa habilitar na configuração ;-)
TOP?
=> chore(tailwind): Add group-hover configuration

packages/orion/src/Form/Field/field.css
Bug encontrado quando o dropdown era multiplo mas tinha a opção `noSelectedLabels` ativada:
Este fix corrige isto.
=> fix(tags-input): Apply padding-top except for no-selected-labels

packages/orion/src/Form/Field/field.css
Esta regra tava aí a 1 ano, quando eu escrevi este componente pela primeira vez.
Cerca de 1 mês atrás Maíra adicionou uma regra mais específica e mais correta na linha 5:
```css
.orion.form .field > label { ... }
```
Esta aqui fez com fosse gerado efeito colateral em componentes que estivesse dentro de um Form.Field mas que fosse toggles, ex:
Por isto estou removendo esta.
=> fix(field-label-rule): Remove unnecessary field label rule

packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/table.css
Adicionando estilo para a prop `selectable
`:
```html
<table selectable ... />
```
**Update 31/03:2020: Mudar comportamento do hover**
Em vez do shadow, vamos só mudar o background. Alinhado com Bruno. 
Depois vamos pensar em uma solução para colocar o shadow...
=> feature(table): Add selectable behavior

packages/orion/src/TagsInput/index.js
pra abrir esse PR https://github.com/inloco/inloco-frontend/pull/849 com a hint no componente, eu tive que colocar uma prop `onBlur`, porém esse método já define uma e a que eu passo acaba ganhando prioridade. fiz assim pra poder fazer as duas chamadas.
=> feat(TagsInput): calls onBlur if passed

packages/orion/src/Dropdown/dropdown.css
Quando um dropdown é do tipo search, o que você estava buscando estava sobrescrevendo com o option selecionado... tipo assim:
OBS: Estou procurando por `Recife`, e o texto do option selecionado está sobrescrevendo.
Dei uma olhada no semantic, e nosso estilo estava faltando esta regra de CSS aqui.
=> fix(dropdown): Fix search filtered text

packages/orion/src/Form/Field/field.css
Estamos com um pequeno bug que faz o placeholder dos inputs em um Form ficarem transparentes. Essa regra está aí para os placeholders não se sobreporem às Labels que ficam dentro do input. Mas acontece que eles continuam transparentes mesmo quando a label sobre no `focus` do componente. 
Estou corrigindo para que essa regra não se aplique em caso de `:focus`. Agora está assim:
Entretanto, não pude corrigir o Dropdown de forma simples, pois a implementação do semântic substitui o "placeholder" (que é só um texto em uma div) pelo valor da opção selecionada ao abrir o Menu... Então deixei ele transparente ainda por enquanto. Se alguém tiver uma ideia de como podemos resolver isso, podemos tentar (talvez em um próximo PR se for mto complexo).
=> fix(Form.Field): avoid hiding placeholder on focus

packages/orion/src/TagsInput/TagsInput.test.js, packages/orion/src/TagsInput/index.js
o time de design ataca novamente
vitinho pediu p esse componente ficar só aceitando vírgulas (ao invés de vírgula, tab e enter) pra não perder tanto a navegação e acessibilidade.
aí eu preferi deixar controlável por prop, caso mude novamente.
=> feat(TagsInput): allows client to control the add values keys via prop

packages/orion/src/Layout/LayoutUserProfile/layoutUserProfile.css
antes com uma foto paisagem:
depois:
=> feat(layoutUserProfile): adds object-cover to image

packages/orion/src/NotificationCenter/notificationCenter.css
Bruno notou que as notificações do Notification Center estavam sem shadow:
Notei que o `Toastr` estava colocando um `overflow: hidden`, o que impossibilitava com shadow de aparecer.
Sobrescrevi esta regra e agora aparece:
=> fix(notification-center): Fix shadow

packages/orion/src/Dropdown/dropdown.css
Notei que se o nosso dropdown tiver muitos itens, ele não tem limite:
Olhei no semantic, e copiei a regra que tem lá pra limitar o tamanho:
=> fix(drodown): Set max height

packages/orion/src/Dropdown/dropdown.css
Notei que O dropdown `multiple` só tava estilizando correto quando também tinha a propriedade `search` ativada.
Com search:
Sem search:
O que eu fiz foi pegar os estilos de tag que estava aplicados a `.orion.dropdown.multiple.search` e subi para `.orion.dropdown.multiple`.
Assim resolveu.
=> fix(dropdown): Fix style when multiple

packages/orion/src/Dropdown/DropdownItem/dropdown-item.css, packages/orion/src/Dropdown/DropdownItem/index.js, packages/orion/src/Dropdown/dropdown.css
- No dropdown de seleção múltipla, usa checkbox ao invés de check;
- Remove a regra `truncate` no description. Agora, descrições longas recebem quebra de linha ao invés de ellipsis;
A ideia é fazer base para esse componente aqui, que será implementado no `inloco-accounts`
Tem um detalhe extra - no caso do Accounts, não é pra ter tags no input.
Isso pode ser alcançável pela prop `renderLabel` do `Dropdown`. Como é um caso específico do Accounts, vou implementar isso por lá mesmo ao invés de generalizar a regra aqui.
=> Feature: checkbox instead of check on Dropdown.Item

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/index.js
O Filter atual tem um botão como trigger:
Em um novo Invision que Bruno me passou, a gente tem um caso que o filtro é algo mais parecido com um Input:
O que este PR faz é permitir que a gente possa passar uma prop `trigger` para o `<Filter />`
=> feature(filter): Add trigger prop

packages/orion/src/Form/Field/field.css
_Quase duas horas procurando esse bug e a solução é só um `>`_
Essa regra no CSS do `Form.Field` é responsável pelo label do campo em si (por exemplo, o label "Email" que fica no input").
Acontecia um problema quando, em algum lugar dentro do field, havia um label que não deveria ser afetado por essa regra (por exemplo, um checkbox). Isso causava esse bug:
Modificando a regra pra que afete apenas labels que são filhos diretos do form field.
=> Fix: only apply label rules to direct form field children

packages/orion/src/Tour/index.js, packages/orion/src/Tour/utils.js
Tinha um pequeno bug no caso em que o primeiro passo era um ancorado (sem seletor) e havia um Modal de welcome (que é exatamente o caso da Tour da Home :facepalm:).
Ao chamar o `useBadgePosition`, estou passando o `currentStep` para procurar a posição da Badge do passo atual. Como estava inicializando o `currentStep` com zero, no primeiro render já será procurando a posição da primeira Badge. Porém, se esse primeiro passo for um com âncora, no qual coloquei para renderizar um elemento placeholder, tal elemento não está renderizado ainda, então a posição da badge fica `null`. Ao passar do modal para o Tour per se, como o `currentStep` permanece zero, o `useEffect` do `useBadgePosition` não vai atualizar a posição. Fazendo com que no primeiro passo, fique sem badge até redimensionar a tela …
=> fix(Tour): setCurrentStep only after welcomeModal

packages/orion/src/Search/search.css
Estranhamente, só acontece com o botão quando ele tá disabled, ou seja, quando a opacidade dele é menor que 1. Isso tá me levando a pensar que existe uma solução melhor, mas não consegui pensar em nenhuma :thinking: 
**O BUG** 
**FIXED**
=> Fix: search results z-index

packages/orion/src/Message/message.css
Olá... Notei que o background o `<Message info />` tava muito clarinha...
Falei com Bruno, e a gente corrigiu:
=> fix(message): Fix Message Info background color

packages/orion/src/Dropdown/dropdown.css
tem 2 ajustes nesse PR:
i) adicionei o css do divider, que nunca existiu, aí o dropdown de produtos tava sem aparecer
ii) mudei a borda do menu de dropdown, que tava gray-900-16, só que, pelo protótipo, ela é mais clara que o divider (que é gray-900-16 tb), aí eu diminuí pra gray-900-8.
protótipo: https://inloco.invisionapp.com/d/main?origin=v7#/console/19947146/417807047/preview?scrollOffset=1389
=> fix(dropdown): adds css styles for divider

packages/orion/src/Card/Card.stories.js, packages/orion/src/Card/card.css, packages/orion/src/Card/index.tsx
Este PR contempla:
* O padding do Card passa de 24px pra 16px;
* O `<Card.Header />` só tem um `font-weight: 500` de diferença pra um texto normal.
* Possibilidade de adicionar um ícone no componente Card.
* Possibilidade de alinhar o conteúdo centralizado.
Este dois últimos são um pouco opiniativos, porque hoje podemos fazer o que quiser com o conteúdo do Card:
```jsx
<Card>
<Card.Content>Todo poder ao seu alcance</Card.Content>
</Card>
```
Mas conversando com Bruno, ele disse que o Card poderia ter um ícone, e ele poderia mudar de cor dependendo do estado(selected), e também o alinhamento. Ex:
Mudando de cor no estado selected:
Mudando o alinhamento:
Baseado neste comportamento padrão, eu resolvi trazer este comportamento pro Card como props adicionais. Se você passar o `icon` como prop …
=> feature(card): Add Icon and center alignment

packages/atomic-bomb/css/base.css
Tem alguns inputs não Orion no `inloco` que estavam com a cor do placeholder diferente. Notei que esta cor estava sendo passado pelo tailwind base class.
Aí tô sobrescrevendo, pra usar a mesma cor dos inputs do Orion.
A gente usa inputs que não são Orion em casos especiais, como o Emoji picker.
=> fix(placeholder): Fix color for non orion inputs

packages/orion/src/Pagination/Pagination.stories.js, packages/orion/src/Pagination/index.js, packages/orion/src/Pagination/pagination.css
Bruno me passou um protótipo em que a paginação aparecendo dentro de um Card. 
Neste tipo de uso, ele pediu pra que os botões de Next e Previous fossem um pouco menores.
Por isso estou adicionando a prop `size` para o Pagination.
Print do protótipo:
Como ficou:
=> feature(Pagination): Add size prop

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/filter.css, packages/orion/src/Filter/index.js
Adiciona a prop `prefix`. Vai servir pra alguns casos especiais onde o filtro é um `except` por exemplo:
OBS: Tentei converter este componente pra Typescript, mas apanhei muito e desisti 😢  Quero voltar nele depois, quando estiver um pouco mais folgado.
=> feature(filter): Add prefix prop

packages/orion/src/ZoomImage/ImageModal.tsx, packages/orion/src/ZoomImage/index.tsx
Como o Modal é renderizado fora do componente principal (um Portal), então estou adicionando a possibilidade de adicionar uma className nele tbm para podermos controlá-lo também
=> feat(ZoomImage): add modalClassName prop

packages/orion/src/TagsInput/TagsInput.stories.js, packages/orion/src/TagsInput/TagsInput.test.js, packages/orion/src/TagsInput/index.js
O que foi feito:
1. onChange: Só é disparado se uma tag for adicionada ou removida, com os valores das tags, e não do search.
2. Se o selectOnBlur estiver ativado, o search vai ser transformado em tag, o que entraria como valor no 1.
3. Por default, selectOnBlur vem `true`, isto faz com que não quebre quem já estava usando o `TagsInput`.
3. Adicionaria o value, que reseta as tags, fazendo o componente ficar controlado.
Tentei adicionar um teste pra quando o `selectOnBlur` estiver ativado, mas não consegui  fazer o evento de Blur ser disparado no React Testing Library.
Na animação abaixo, eu apenas tiro o foco do elemento, para o search ser transformado:
OBS: Antes, eu alinhei este comportamento com @llaryssa e @brunoperruci-inloco .
=> feature(TagsInput): Allow TagsInput to be controlled

packages/orion/src/TagsInput/TagsInput.stories.js, packages/orion/src/TagsInput/index.js
Pô, notei um bug quando ele estava controlado, e o `value` era modificado do lado de fora do componente:
Antes:
Depois:
O que acontece é que o setState estava considerando o state interior do componente pra setar o novo state.
A correção foi ele usar o `values`, que é o valor correto.
=> fix(tags-input): Fix behavior when controlled

packages/orion/src/MultiSelectFilter/MultiSelectFilter.stories.js, packages/orion/src/MultiSelectFilter/index.js
Permite que o `<MultiSelectFilter />` aceite uma prop `children`:
OBS: Os botões `Show Only` e `Show All Except` são o coteúdo do `children`.
=> feature(multi-select-filter): Allow children to be passed

packages/orion/src/Table/Table.stories.js, packages/orion/src/Table/index.js, packages/orion/src/Table/table.css
Adicionando o componente `Table.Footer` que ainda não estava incluído. Segui o estilo do protótipo da página de credenciais:
Storybook:
=> feat(Table): add Table.Footer

packages/orion/src/NotificationCenter/notificationCenter.css
Na versão 6.0.0 do `react-toastify` está sendo usado o  `transform` pra mover o toast pro centro, ao invés do `margin-left` negativo ([Release notes](https://github.com/fkhadra/react-toastify/releases/tag/v6.0.0))
Mas aqui ainda estávamos "sobreescrevendo" o [agora inexistente inexistente] margin-left, fazendo o toast ter dois deslocamentos para a esquerda e deixar de estar centralizado.
Estou removendo a regra pra ficar okay
=> fix(NotificationCenter): remove margin-left for positioning

packages/orion/src/FilterBar/FilterBar.stories.js, packages/orion/src/FilterBar/index.js
O componente `<FilterBar />` só aceitava ter filhos que tivessem a prop name, porque só foi usado com o `<FilterBar.Filter />`.
Mas tem alguns casos que a gente precisa exibir um filtro dentro do FilterBar condicionalmente, ou precisamos adicionar um ícone, e aí o `<FilterBar />` quebrava.
Com esta alteração, é permitido passar qualquer tipo de filho pro `<FilterBar />`.
=> feature(filter): Allow FilterBar to have another children types

packages/atomic-bomb/tailwind.config.js
há um tempo, bruno vem mandando protótipos que tem lugares onde o line-height tá diferente do que a gente adota (e do que tem no orion). conversei com ele e isso resultou nesse card https://www.notion.so/inlocoglobal/Line-height-da-fonte-12px-t-14px-ao-inv-s-de-18px-b14d69660e104e5fa54e5338feeed226. comecei a resolver o card há um tempo atrás mas ele é muito arriscado, pq mexe em muitaaaa coisa. acredito que essa mudança tenha que fazer passo a passo com um designer.
como ainda não vamos mudar tudo, adicionei esse line height de 18px ao orion pra ir colocando em alguns textos do frontend. o que acham?
=> feat(tailwing.config.js): adds 18px lineHeight config

packages/orion/src/Dialog/dialog.css
Me cocei muito pra não subir este ajuste direto no master, mas Bruno pediu que o dialog sempre tenha o width de 384px...
Antes:
Depois:
=> fix(dialog): Set fixed width

packages/orion/src/Layout/LayoutUserProfile/UserProfileButton/index.js
Nas novas mudanças da navegação, foi incluído os botões de home e settings dentro das orgs não selecionadas.
Esses botões são links (`<a />`), mas o item da org tbm é clicável, e é um link também.
Não podemos implementar um link dentro de link pois vai contra as validações da DOM
> Warning: validateDOMNesting(...): \<a> cannot appear as a descendant of \<a>
Consegui resolver isso transformando os itens e botões em `<a />` apenas quando necessário com um state, usando `onMouseEnter` e `onMouseLeave`.
```
<Layout.UserProfile.Item
...
{...(!over && { as: 'a', href: '/item' })}>
...
<Layout.UserProfile.Button
tooltip="Tooltip"
{...(over && {
as: 'a',
href: '/button'
})}
onMouseEnter={() => setOver(true)}
onMouseLeave={() => setOver(false)}>
<Icon name="home" />
</Layout.UserProfile.Button> …
```
=> feat(LayoutUserProfile): add tooltipOpen prop

packages/orion/src/Dropdown/DropdownItem/dropdown-item.css
Victinho me chamou a atenção sobre esse dropdown, não era pra o item ficar em negrito ao ser selecionado:
Victinho e Bruno aproveitaram e decidiram remover esse negrito de todos os outros dropdowns, incluindo o que não é multiple selection. A ideia é que o item selecionado já tem o background cinza destacado, então é reduntante.
=> Feature: normal font on active item in dropdown

packages/orion/src/Layout/LayoutUserProfile/index.js, packages/orion/src/Layout/LayoutUserProfile/layoutUserProfile.css
**Antes**
**Depois**
O `max-width: 108px` foi pego do [Invision](https://inloco.invisionapp.com/d/main?origin=v7#/console/19947146/424694082/inspect?scrollOffset=1791). O dropdown todo tem que ser 192px, mas pro truncate funcionar, o limite tem que ficar no pai imediato.
=> Fix: truncate username and label (organization name)

packages/atomic-bomb/tailwind.config.js
Para usar no `ImageUploader`, mas pode ser útil em outros casos.
=> Feature: add border transparent

packages/orion/src/Input/input.css
=> feat(input.css): adds padding in the right

packages/orion/src/Icon/index.js
Mesmo adicionando o role e o name, o ícone ainda não estava acessível com `getByRole("img", { name: "xalala" })`. Adicionei o `aria-label` para corrigir isso.
=> feature(Icon): add aria-label

packages/atomic-bomb/css/base.css
A cor implementada para os links estava um tom mais escuro em relação aos protótipos:
https://inloco.invisionapp.com/d/main?origin=v7#/console/17711749/367438614/inspect?scrollOffset=641
=> chore(atomic-bomb): set lighter wave shade for links

packages/orion/src/Layout/LayoutUserProfile/layoutUserProfile.css
O estilo dos links foi atualizado nas últimas mudanças do orion. Antes era regular wave-600, agora é medium wave-500.
A mudança já foi aplicada no css base daqui, mas neste link havia uma definição explícita das cores, o que estava sobreescrevendo a dos links e acabou não sofrendo mudança aqui.
Essa definição não é necessária para o caso default que esse `EditLink` é um `a`, mas estava sendo aplicado de qqr forma. Então, além de atualizar para o novo estilo, deixei aplicando apenas se o elemento for diferente de `a` (o que pode ser definido pela prop `as`).
=> fix(layoutUserProfile): change editLink to new link style

packages/orion/src/Menu/menu.css
Efeito colateral de ter setado `font-weight` no `<a>`, os itens de menu ficaram `bold`.
Este PR faz eles voltarem a ser `normal`.
=> fix(menu-item): Set correct font-weight

packages/orion/src/Dropdown/dropdown.css
Outro efeito colateral aqui...
No Dropdown multiple, o Semantic seta um `<Label />` as `a `.
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L938
Antes:
Depois:
=> fix(dropdown-multiple): Set font-normal with dropdown multiple

packages/orion/src/Dropdown/dropdown.css
Mais um que tinha sido afetado pelo font-weight dos links.
No exemplo abaixo, coloquei `as='a'` no "Account":
Antes
Depois
=> fix(dropdown): set font-normal to dropdown text

packages/orion/src/Form/Field/field.css
Quando o textarea tava dentro de um `Field`, a borda não estava ficando vermelha em um erro.
=> fix(form-field): Set textarea border red when error

packages/orion/src/Layout/layout.css
Último afetado aqui, segundo a [revisão de Bruno](https://www.notion.so/inlocoglobal/Fix-link-style-after-Orion-update-5a60530784e349dbb72b0bbe167d59f4)
Se usar um `a`:
Antes:
Depois:
=> fix(layout): enforce apps dropdown item fontWeight and color

packages/atomic-bomb/tailwind.config.js
Na `v1.7` do tailwind, as classes `col-gap-x` e `row-gap-x` estão sendo depreciadas. Changelog: [link](https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.7.0)
Com isso, surge um novo alerta na hora do build sugerindo a troca pelas regras novas equivalentes:
Já estou trocando no `inloco-frontend` neste PR: https://github.com/inloco/inloco-frontend/pull/1402
No `4apps-js` e no `inloco-accounts` não encontrei estas regras sendo utilizadas.
Então estou setando esta flag como recomendado na documentação do Tailwind. Isso ira remover o alerta e as regras depreciadas do build na próxima release.
=> chore(tailwind): set removeDeprecatedGapUtilities flag

packages/orion/src/Icon/Icon.stories.js, packages/orion/src/Icon/icon.css
No `Inloco` a gente precisou usar o `loading icon` com o background mais escuro... aí ficou bem ruim..
Depois de fazer vários ajustes com @brunoperruci-inloco , encontramos as cores corretas pra ambos os backgrounds:
=> feature(loading-icon): Adjust colors for inverted state

packages/orion/src/Dropdown/DropdownItem/index.js
Tinha um bug cabuloso no Dropdown múltiplo com checkbox...
Se o Dropdown tiver uma `max-height` para os itens, e você clicar em cima do checkbox, o scroll subia pro primeiro item.
ex:
Aí adicionei um `user-events-none` pra que os clicks dentro do checkbox não sejam reportados, já que temos um evento de click no wrapper do item.
Depois:
=> fix(dropdown): Fix dropdown multiple checkbox click

packages/orion/package.json
No último release, o componente de Flags não funcionou pq o arquivo `.png` com os sprites não foi incluído no pacote. Então adicionei o path para `assets` no `files` do `package.json`.
Also, percebi o path `**/*.js` estava fazendo incluir alguns `.js` [que eu acho que são] desnecessários no bundle, como os arquivos em `src` (o que se usa de fato está em `dist`) e alguns arquivos de configuração no ambiente de dev.
Então atualizei para incluir apenas os `.js` dentro de `/dist`, esta mudança faz sentido?
Eu não sei alguma forma de testar se isso ficou okay além de fazer de fato o release do pacote no npm. Vocês têm alguma ideia de como eu posso gerar e inspecionar este bundle localmente, sem precisar fazer um release real?
=> fix(package.json): add assets to "files" paths

packages/orion/src/Dropdown/DropdownItem/index.js
Em um PR passado ([PR-883](https://github.com/inloco/orion/pull/883)), eu tinha colocado o `pointer-events-none` no div inteiro responsável pelo DropdownItem.
Isto causou um efeito colateral no `Inloco`, onde havia um conteúdo com o evento de click configurado.
Na verdade eu só preciso desconsiderar o evento do click no checkbox em si.
=> fix(dropdown): Clicking on the checkbox

packages/orion/src/StatusTag/StatusTag.stories.js, packages/orion/src/StatusTag/statusTag.css, packages/orion/src/utils/sizes.js, packages/orion/src/utils/stories.js
Tem um StatusTag maior agora.
Eu adicionei um `size='large'`.
Como é o primeiro componente com `size='large'`. Eu precisei criar outras constantes de sizes (`ThreeSizes`), pra não interferir nos outros componentes que já usam as constantes atuais.
Se alguém tiver uma idéia melhor...
=> feature(status-tag): Add large size

packages/orion/src/Popup/popup.css
Falei com Bruno, e ele disse que não tem mais o line-height de 14 no Popup/InfoIcon.
Antes:
Depois:
=> fix(popup): Remove line-height 14

packages/atomic-bomb/css/base.css, packages/orion/src/Layout/layout.css
Olá!
Bruno me pediu através deste card: https://www.notion.so/inlocoglobal/Feature-review-c81b47283400497d9c26c51ee5e60fd2?p=a33b5009d0394982b8f6c93d5b77d15d
para sempre mostrar o scroll vertical, independente do conteúdo.
Ficou assim:
Isto é pra evitar o "samba" que acontece quando muda de uma tela que não tem scroll pra uma tela que tem.
Achei esquisito, então qualquer coisa, reclame com ele 😆 
**Update 17:39**
@TCezarRod sugeriu uma solução melhor, e subi o ajuste!!!
=> feature(scroll-y): Always show scroll vertically

packages/orion/src/Dialog/dialog.css
Atualmente o Dialog está com o ícone sólido para o estado default
Mas no Invision, está definido para usar o ícone outlined. Então estou trocando e agora está assim:
=> feat(Dialog): change info icon to outline

packages/orion/src/Pagination/Pagination.stories.js, packages/orion/src/Pagination/index.js
Adicionando o i18n.language no Pagination, pra a gente poder formatar o totalItems:
O TotalItems não pode ser uma string, porque é feito um calculo em cima dele, então a formatação tem que ser feita no Orion mesmo.
=> feature(Pagination): Add language param

packages/orion/src/DatepickerInput/datepickerInput.css, packages/orion/src/Layout/layout.css, packages/orion/src/StatusTag/statusTag.css
O valor `fit-content` para `width` é experimental e não é suportada em alguns browsers
https://developer.mozilla.org/pt-BR/docs/Web/CSS/width
Então estou removendo a regra de onde faltava aqui no Orion.
No `Layout` o `fit-content` era desnecessário, o dropdown de apps funciona sem ele
No `StatusTag` e `DatePickerInput`, susbstituí por `w-auto`. Para isso, precisei trocar o display para um `inline` (flex ou block). Antes de fazer isso, chequei no `inloco-frontend` e no `4apps-js` se essa mudança no display influenciaria em algo. Mas está tudo certo. Só o `StatusTag` está sendo usado nos projetos, e a mudança não traz problemas. O `DatePicker` não é usado em nenhum dos dois projetos.
=> Feature/remove fit-content

packages/orion/package.json, packages/orion/src/Dropdown/DropdownItem/dropdown-item.css, packages/orion/src/Dropdown/dropdown.css, packages/orion/src/Popup/popup.css, yarn.lock
Eu quebrei em commits e acho que facilita revisando por eles:
1. Faz o upgrade pra v2.0.1 do semantic.
2. Atualiza o dropdown múltiplo com imagens. No antigo, o item selecionado não ficava com a imagem, agora fica:
3. Ajustei o `pointing` do Popup / Tooltip / Derivados... 
4. No dropdown, precisamos esconder o placeholder quando o item tá selecionado. No anterior o placeholder era removido.
OBS: Passei de componente em componente, e fiz alguns testes, mas pode ser que tenha escapado alguma coisa, ou então que o uso de um componente no `inloco-frontend` ou `4apps-js` faça ele se comportar diferente. Fiquem atentos caso encontrem algo estranho.
=> Chore/update semantic ui to 2.0.1

packages/orion/src/Dropdown/Dropdown.stories.js, packages/orion/src/Dropdown/DropdownItem/dropdown-item.css
O Dropdown.Item dá suporte ao `disabled` mas ainda não tínhamos adicionado o estilo. Estou fazendo-o aqui
No GIF não dá pra perceber, mas eu estava clicando nos itens disabled. Apenas o que não está desabilitado gera eventos.
=> feat(Dropdown): add disabled style for items

packages/orion/src/Popup/popup.css
Corrigindo o posicionamento da setinha do popup nos casos de center right e center left. Antes estava assim:
Então tirei o `top-auto` (já tinha um top: 50% que tava sendo sobreescrito) e usei o `transform` pra centralizar. Usei o transform do tailwind pra poder compor com o rotate-45 que já existia antes. Daí conseguimos montar o transform em lugares diferentes :D 
Agora está assim:
=> fix(popup): center popup arrow for center right and left

packages/orion/src/Datepicker/ReactDatesDatepicker/index.js, packages/orion/src/Filter/index.js
Uma leve mudança nos botões do calendário. Na nova versão do Orion, o estado de resting do botão é sem o círculo cinza.
Antes:
Depois:
=> feat(Datepicker): set nav buttons as subtle

packages/orion/src/Table/index.js, packages/orion/src/Table/table.css
Os estilos das linhas da tabela estão definidos diretamente com a tag `tr`. Isso faz com que não possamos trocar o elemento usado para a linha (usar um `a`, por exemplo) ou o estilo se perderia. E.g.:
Então estou adicionando uma classe no Table.Row e trocando as regras de estilo para usarem esta classe. Assim, podemos trocar o elemento da linha. 
Isso vai ser útil na tabela dos dashes de POV para linkar para a página de detalhes, ao invés de usar o state + redirect.
=> feat(Table): set table row styles for classname instead of tag

packages/orion/src/Table/TableCell/index.js, packages/orion/src/Table/table.css
Okay, outra tentativa de solução do problema dos links na tabela.
Já que não podemos transformar a `tr` em outro elemento, pensei em colocar o link em cada `Table.Cell`. Porém, se eu passar o `as` para o `Table.Cell` ele vai transforma o `td` no que eu disser. E isso tbm torna o html inválido, pq o `tr` tbm tem restrições nos elementos filhos permitidos:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#technical_summary
Então estou capturando aqui a prop `as` (e a `href` tbm, pq se repassada, a inferencia seria feita no `SemanticTable.Cell`) e passando para o inner-cell.
Isso traz a transformação em URL que quero ao nível da célula. O lado negativo é q se eu precisar da linha toda como um Link, preciso passar a prop em cada `Table.Cell`. Mas acho q isso resolve nosso problema …
=> Feature/Table.cell 'as' prop

packages/atomic-bomb/css/font.css, packages/atomic-bomb/tailwind.config.js, packages/orion/src/Typography.stories.js
Precisamos da variante `thin` (font-weight 200) da fonte `Neue Haas Grotesk Display`, mas ainda não tínhamos aqui.
Pedi para Cris pegar para mim lá no [site da Adobe](https://fonts.adobe.com/fonts/neue-haas-grotesk#fonts-section)
Eu poderia apenas importar da url https://use.typekit.net/jsf0fxl.css, que já define todos esses font-faces, mas ao fazer isso notei que a variante `Display` tem um fontweight diferente da variante `Text` para os pesos `normal` e `medium`. Para o `Display` os normal e medium são 500 e 600, respectivamente, mas nas nossas regras, eles são 400 e 500.
Então mantive a declaração dos `font-face` direto aqui no `font.css` para que pudesse ajustar de acordo.
O medium era o único que tínhamos disponível para a Display, e agora podemos usar tbm `normal` e `thin`. Mas a …
=> Feature/Typography font-weight

packages/orion/src/StatusTag/statusTag.css
Conversei com Cristiano, e notamos que os status do `<StatusTag />` estavam errados para o `neutral`.
Antes o `neutral` estava definido pra ser um `space`, e com o rebranding, ele se tornou um `purple`, o que o deixou assim:
Sendo que isto não é nada neutro. Então Cristiano decidiu que o Neutro deveria ficar assim:
Ainda existe o status `inactive`,  que é o neutro, mais claro:
Como podem ver, os ajustes no Orion foram mínimos, porém no `inloco-frontend` há várias referências ao `inactive`, quando na verdade ele deveria estar apontando para o `neutral`. Então vai rolar um refactoring por lá também.
=> feature(status-tag): Change colors

package.json, packages/atomic-bomb/package.json, packages/orion/package.json, yarn.lock
Reverts inloco/orion#1058
The upgrades from that PR introduces some inconsistencies because of other packages that have yet to upgrade `postcss` that are breaking the build. So I'm reverting them until we can upgrade all of these dependencies.
=> Revert "chore(deps-dev): bump postcss-import from 12.0.1 to 14.0.1"

packages/orion/src/Layout/Layout.stories.js, packages/orion/src/Layout/LayoutUserProfile/index.js, packages/orion/src/Layout/layout.css
Adicionei uma prop `footer` no `<Layout.UserProfile />`.
Diante de como está implementado, achei a opção mais genérica.
O footer vai servir pra adicionar os links no footer do UserProfile:
O que achas @marcelscr ?
=> feature(user-profile-footer): Add user pofile footer

packages/orion/src/Filter/Filter.stories.js, packages/orion/src/Filter/Filter.test.js, packages/orion/src/Filter/filter.css, packages/orion/src/Filter/index.js
Na lista de installations, o filtro de AppId vai ser obrigatório, não sendo possível limpá-lo através dos botões de clear - sempre terá um valor.
Com isso, adicionei essa prop pra ser possível esconder os botões de clear no componente de Filter.
=> feature(Filter): add the clearable prop

packages/orion/src/Layout/LayoutSidebar/index.js, packages/orion/src/Layout/layout.css
Encontrei alguns problemas quando coloquei o Layout no produto:
1. A margin do main estava em 230px, enquanto o Sidebar tinha 238px. Notei que no Storybook funciona porque existe um elemento "root" do storybook que tinha margin de 8px e inteferia nisto. Mas no produto ficava desalinhado.
2. O Main estava com 100% de width com + 238px de margin, o que dava ruim. Tirando o 100% resolve.
3. Quando o logo é passado via props, os estilos não estava sendo setados pra ele.
Antes:
Depois:
=> fix(layout): Fix layout spacement issues

packages/orion/src/Layout/layout.css
Corrigindo o estilo do item menu on hover:
=> fix(sidebar-menu): Fix menu items hover style
